language: node_js
node_js:
  "node"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install:
  - ~/.yarn/bin/yarn
  - (cd backend && ~/.yarn/bin/yarn)
  - (cd frontend && ~/.yarn/bin/yarn)
script:
  - ~/.yarn/bin/yarn run flow check
  - (cd frontend && ~/.yarn/bin/yarn run build)
cache: yarn
