language: node_js
node_js:
  "node"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install:
  - yarn
  - (cd backend && yarn)
  - (cd frontend && yarn)
test:
  - yarn run flow
cache: yarn
