ALTER TABLE characters ALTER COLUMN name DROP NOT NULL;

ALTER TABLE matches ALTER COLUMN "winnerId" DROP NOT NULL;
ALTER TABLE matches ALTER COLUMN "player1Id" DROP NOT NULL;
ALTER TABLE matches ALTER COLUMN "player2Id" DROP NOT NULL;
ALTER TABLE matches ALTER COLUMN "character1Id" DROP NOT NULL;
ALTER TABLE matches ALTER COLUMN "character2Id" DROP NOT NULL;

ALTER TABLE players ALTER COLUMN name DROP NOT NULL;
