ALTER TABLE characters ALTER COLUMN name SET NOT NULL;

ALTER TABLE matches ALTER COLUMN "winnerId" SET NOT NULL;
ALTER TABLE matches ALTER COLUMN "player1Id" SET NOT NULL;
ALTER TABLE matches ALTER COLUMN "player2Id" SET NOT NULL;
ALTER TABLE matches ALTER COLUMN "character1Id" SET NOT NULL;
ALTER TABLE matches ALTER COLUMN "character2Id" SET NOT NULL;

ALTER TABLE players ALTER COLUMN name SET NOT NULL;
